name: Test / Build / Release
on:
  push:
    branches:
      - homolog
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  id-token: write

jobs:
  release-homolog:
    name: Release-homolog
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
      PROJECT_ID: fastech-homolog
      REGISTRY: gcr.io
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_HOMOLOG }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker ${{ env.REGISTRY }} -q

      - name: Build and push image
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
          VERSION: ${{ github.sha }}
        run: |
          docker buildx build \
            --build-arg GITHUB_TOKEN=${{ secrets.RELEASE_GH_TOKEN }} \
            --build-arg GIT_COMMIT_HASH=${ GITHUB_SHA::7 } \
            -t "${{ env.IMAGE }}:${{ env.VERSION }}:latest" \
            --push . 

      - name: Show pushed tags
        run: |
          echo "✅ Pushed:"
          echo " - $${{ env.IMAGE }}:${{ env.VERSION }}"
